### ISSUE TITLE
Criar um manual do contribuidor

### ISSUE THREAD

**Issue by lipemorais** [AfroPython/tutorial#20]
**Qual é o ponto de melhoria?**
A ideia é facilitar a vida dos novos contribuidores do projeto e assim receber mais contribuições.

**Como isso pode ser resolvido?**
Criar um arquivo sobre como contribuir e mencionar ele no `README.md`

**Quem poderia ajudar com isso?**
Qual quer pessoa que esteja interessada.

**Comment by Amandasv** [comment]
Esse foi fechado no PR #24
