### ISSUE TITLE
Ajustar texto da "Introdução a linha de comando > O básico > Entrando nas pastas"

### ISSUE THREAD

**Issue by thainararogerio** [AfroPython/tutorial#26]
Acho que poderíamos modificar o seguinte texto:

> Dica de profissional: se você digitar cd D e apertar a tecla tab no seu teclado, a linha de comando irá preencher automaticamente o resto do nome para que você possa navegar rapidamente.
> Se houver mais de uma pasta que comece com "D", aperte a tecla tab duas vezes para obter uma lista de opções.

Para entrar no contexto da seção.

Só substituindo o "cd D" por "cd a" de "afropython", porque senão fica fora de contexto esse trecho.
Isso porque nessa mesmo seção, um pouco antes, estamos falando da pasta "afropython".

Posso mudar isso depois do PR.

**Comment by Amandasv** [comment]
Booa @thainararogerio :) 
Você conseguirá ver isso? Ou qualquer coisa me avisa que pego aqui....

**Comment by Amandasv** [comment]
Arrumei nesse commit aqui: [#15ca675](https://github.com/AfroPython/tutorial/pull/32/commits/15ca67535e110e3fe97cbdb6dcfa21141fa9cab8)
