### ISSUE TITLE
Sessão *Salve o código* - E se não?

### ISSUE THREAD

**Issue by lipemorais** [AfroPython/tutorial#5]
**Qual é o ponto de melhoria?**
A ideia dessa issue é adicionar uma sessão chamada `E se não?`  ao tutorial logo depois da sessão `if...elif...else`  baseado nessa sessão to tutorial do Django Girls de Caxias do Sul: [E se não?](https://docs.google.com/document/d/15asJrEfA6FvN1jHBqYwVDWc_e1MsUo9YH_on5HYR_Cc/edit#heading=h.fmsaz18xnrr)

**Como isso pode ser resolvido?**
Utilize as referências ali em cima para criar um markdown para esse capítulo e adicionar certinho no `SUMMARY.md`

**Quem poderia ajudar com isso?**
Eu acredito que a @cynthiapereira mas qualquer pessoa poderia que tiver interesse pode ajudar com essa issue.

**Comment by carolmoers** [comment]
A sessão `if...elif...else` também estava dentro da sessão de Python ao invés da sessão "Salve o código!".

Esse [PR](https://github.com/AfroPython/tutorial/pull/12) move a sessão `if...elif...else` para a de Salve o código e também já cria uma sessão para `E se não?` seguindo o `SUMMARY.md`
